require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pharmx' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-firebase-push-notifications', :path => '../node_modules/react-native-firebase-push-notifications'

  target 'pharmxTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'pharmx-tvOS' do
  # Pods for pharmx-tvOS

  target 'pharmx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
